# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Userprofile

on:
  pull_request:
    branches: [ main ]
    types:
      - "closed"
  workflow_dispatch:

jobs:
  pushToACR:
    runs-on: ubuntu-latest
    environment: TEST
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - name: Build the Docker image
      run: |
        cd apis/userprofile
        docker build . --file Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/userprofile:${{ github.sha }}
      working-directory: ./main
   
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_SECRET }}
    - run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/userprofile:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackw0f57h53userprofile'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.ACR_LOGIN_SERVER }}/userprofile:${{ github.sha }}'
        slot-name: 'openhackw0f57h53userprofile-staging'

    - name: Check Slot
      id: slot
      run: |
        scripts/polling.sh "https://openhackw0f57h53userprofile-staging.azurewebsites.net"
      shell: bash

    - name: Deploy to production
      if: steps.id.slot.status == '200'
      run: |
        az webapp deployment slot swap  -g openhackw0f57h53rg -n openhackw0f57h53userprofile --slot staging --target-slot testswap