# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push: 
    paths:
      - "apis/userprofile/**"
    branches:
      - "feature/*"
      - "bugfix/*"
    
    
  pull_request:
    branches: [ main ]
    types:
      - "opened"
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: apis/userprofile/package-lock.json
    - run: |
        cd apis/userprofile
        npm ci
        npm run build --if-present
        npm test
    - name: Create issue
      if: failure()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE_CUSTOM.md
