# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push: 
    paths:
      - "apis/userprofile/**"
      - ".github/workflows/**"
    branches:
      - "feature/*"
      - "bugfix/*"
    
    
  pull_request:
    branches: [ main ]
    types:
      - "opened"
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: apis/userprofile/package-lock.json
    - run: |
        cd apis/userprofile
        npm ci
        npm run build --if-present
        npm test
    - name: Create issue
      if: failure()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE_CUSTOM.md

  # pushToACR:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment: TEST
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #     with:
  #       path: main
  #   - name: Build the Docker image
  #     run: |
  #       cd apis/userprofile
  #       docker build . --file Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/userprofile:${{ github.sha }}
  #     working-directory: ./main
   
  #   - uses: azure/docker-login@v1
  #     with:
  #       login-server: ${{ secrets.ACR_LOGIN_SERVER }}
  #       username: ${{ secrets.ACR_USER }}
  #       password: ${{ secrets.ACR_SECRET }}
  #   - run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/userprofile:${{ github.sha }}
